name: Build

on:
  push:
    branches: ["main", "singleton", "java"]
    paths:
    - "**.java"
    - "**.properties"
    - "core/"
    - "build.gradle"
    - "**.gradle"
    - ".github/workflows/build.yml"

  workflow_dispatch:

jobs:
  OnlyPCBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: chmod
      run: chmod +x gradlew
    - name: Build mod jar
      run: ./gradlew deployPackPCONLY
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}-DesktopOnly
        path: build/libs/GRavillaso-DesktopOnly.jar

   
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v2.0.1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: build-tools
      run: sdkmanager "build-tools;30.0.0"
    - name: Add Android SDK to PATH
      run: echo "${ANDROID_HOME}/build-tools/30.0.0" >> $GITHUB_PATH

    - name: chmod
      run: chmod +x gradlew
    - name: Build mod jar
      run: ./gradlew deployPack
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}
        path: build/libs/**.jar
